# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:01
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_name', models.CharField(max_length=100)),
                ('fm_slug', autoslug.fields.AutoSlugField(editable=True, populate_from='fm_name', unique=True)),
                ('fm_description', models.TextField(blank=True)),
                ('fm_picture', models.ImageField(blank=True, upload_to='fm_images')),
                ('fm_banner_picture', models.ImageField(blank=True, upload_to='fm_images')),
                ('fm_contact_name', models.CharField(max_length=30)),
                ('fm_contact_email', models.EmailField(max_length=254)),
                ('fm_website', models.URLField(blank=True)),
                ('fm_facility_type', models.CharField(blank=True, max_length=30)),
                ('fm_county', models.CharField(blank=True, max_length=30)),
                ('fm_address', models.CharField(blank=True, max_length=30)),
                ('fm_programs_accepted', models.CharField(blank=True, max_length=30)),
                ('fm_phone', localflavor.us.models.PhoneNumberField(blank=True)),
                ('fm_hrs_of_operation', models.CharField(blank=True, max_length=30)),
                ('fm_seasons_of_operation', models.CharField(blank=True, max_length=30)),
                ('fm_handicap_accessible', models.CharField(blank=True, max_length=30)),
                ('fm_iframe_url', models.URLField(blank=True)),
                ('fm_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_picture', models.ImageField(blank=True, upload_to='rating_images')),
                ('rating', models.PositiveIntegerField()),
                ('rating_comment', models.TextField()),
                ('rating_created', models.DateTimeField(auto_now_add=True)),
                ('rating_fm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_app.FarmersMarket')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_slug', autoslug.fields.AutoSlugField(editable=True, populate_from='fm_name', unique=True)),
                ('vendor_description', models.TextField(blank=True)),
                ('vendor_picture', models.ImageField(blank=True, upload_to='vendor_images')),
                ('vendor_banner_picture', models.ImageField(blank=True, upload_to='vendor_images')),
                ('vendor_contact_name', models.CharField(max_length=30)),
                ('vendor_contact_email', models.EmailField(max_length=254)),
                ('vendor_website', models.URLField(blank=True)),
                ('vendor_phone', localflavor.us.models.PhoneNumberField(blank=True)),
                ('vendor_updated', models.DateTimeField(auto_now=True)),
                ('at_farmers_market', models.ManyToManyField(to='review_app.FarmersMarket')),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_app.VendorType'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_app.Vendor'),
        ),
    ]
