# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmersmarket',
            name='fm_county',
        ),
        migrations.AlterField(
            model_name='farmersmarket',
            name='fm_facility_type',
            field=models.CharField(blank=True, choices=[('Open-Air', 'Open-Air'), ('Open-Air/Covered', 'Open-Air/Covered')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Farmers Market', 'Farmers Market'), ('Vendor', 'Vendor'), ('Reviewer', 'Reviewer')], max_length=15),
        ),
    ]
