# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 18:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_auto_20160719_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersmarket',
            name='fm_county',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='farmersmarket',
            name='fm_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='fm_name', unique=True),
        ),
    ]
