# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:28
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_auto_20160721_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='vendor_name', unique=True),
        ),
    ]
