# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review_app', '0005_auto_20160722_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_present', models.BooleanField()),
                ('status_picture', models.ImageField(blank=True, upload_to='status_images')),
                ('status_comment', models.TextField(blank=True)),
                ('status_created', models.DateTimeField(auto_now_add=True)),
                ('status_fm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_app.FarmersMarket')),
                ('status_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_app.Vendor')),
            ],
        ),
    ]
