# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0006_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-status_created']},
        ),
    ]
