# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 00:36
from __future__ import unicode_literals

from django.db import migrations
import csv
from django.template.defaultfilters import slugify


def verndor_type_import(apps, schema_editor):
    VendorType = apps.get_model("review_app", "VendorType")
    with open("review_app/data/vendor_types.csv") as infile:
        vendor_types = csv.reader(infile)
        for row in vendor_types:
            VendorType.objects.create(vendor_type=row[1])

    # raise Exception("1 yay")


def mainst_vendor_import(apps, schema_editor):
    Vendor = apps.get_model("review_app", "Vendor")
    FarmersMarket = apps.get_model("review_app", "FarmersMarket")
    with open("review_app/data/gvl_mainst_vendors.csv") as infile:
        ms_vendors = csv.reader(infile)
        fm = FarmersMarket.objects.get(fm_name="TD Saturday Market")
        for row in ms_vendors:
            vendor_slug = slugify(row[0])
            vendor = Vendor.objects.create(vendor_name=row[0], vendor_slug=vendor_slug,
            vendor_description=row[1], vendor_website=row[2])
            # http://stackoverflow.com/questions/12764347/django-invalid-keyword-argument-for-this-function
            vendor.save()
            vendor.at_farmers_market.add(fm)

    # raise Exception("2 yay")

class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0006_auto_20160720_0036'),
    ]

    operations = [
        migrations.RunPython(verndor_type_import),
        migrations.RunPython(mainst_vendor_import),
    ]
