# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_auto_20160728_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmersmarket',
            options={'ordering': ['fm_name']},
        ),
        migrations.AlterField(
            model_name='status',
            name='status_picture',
            field=models.ImageField(blank=True, null=True, upload_to='status_images'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No Response', 'No Response')], default='No Response', max_length=10),
        ),
    ]
