# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0008_auto_20160730_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersmarket',
            name='fm_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmersmarket',
            name='fm_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No Response', 'No Response')], default='No Response', max_length=11),
        ),
    ]
