# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0010_auto_20160731_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_fm_like',
            field=models.ManyToManyField(related_name='fm_liked_by', to='review_app.FarmersMarket'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_vendor_like',
            field=models.ManyToManyField(related_name='vendor_liked_by', to='review_app.Vendor'),
        ),
    ]
